[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3.5"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.96"
tokio-postgres = "0.7.8"